# Generated by Django 5.2.3 on 2025-09-16 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_datasets', '0002_dataset_head_context_dataset_plots_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='The ZIP file containing the model on Autogluon format', null=True, upload_to='MLmodels/')),
                ('name', models.CharField(help_text='Name of the model', max_length=100)),
                ('description', models.TextField(blank=True, help_text="A brief description about the model and it's purpouse", null=True)),
                ('features', models.JSONField(blank=True, help_text='List of features used by the model', null=True)),
                ('target', models.CharField(help_text='Target variable name', max_length=100)),
                ('model_type', models.CharField(default='TabularPredictor', help_text='Type of model, e.g., TabularPredictor', max_length=100)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', help_text='The current status of the model.', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the dataset was uploaded')),
                ('is_evaluated', models.BooleanField(default=False, help_text='Indicates if the model has been evaluated.')),
                ('evaluation_date', models.DateTimeField(blank=True, help_text='Date and time when the model was last evaluated.', null=True)),
                ('evaluation_metrics', models.JSONField(blank=True, help_text='Key-value pairs of evaluation metrics (e.g., accuracy, F1-score).', null=True)),
                ('evaluation_plots', models.JSONField(blank=True, help_text='Cached plots from model evaluation or prediction simulations.', null=True)),
                ('related_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_datasets.dataset')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the model', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
