# Generated by Django 5.2.3 on 2025-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_MLmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='training_duration',
            field=models.DurationField(blank=True, help_text='Time taken to train the model.', null=True),
        ),
    ]
