# Generated by Django 5.2.3 on 2025-09-25 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_MLmodels', '0001_initial'),
        ('manage_datasets', '0002_dataset_head_context_dataset_plots_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_metrics', models.JSONField()),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='manage_datasets.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='manage_MLmodels.mlmodel')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
