# Generated by Django 5.2.3 on 2025-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_testresult_evaluation_plots'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='leaderboard_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
