# Generated by Django 4.2.7 on 2025-10-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_testresult_leaderboard_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='evaluation_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
