# Generated by Django 5.2.3 on 2025-09-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_MLmodels', '0002_mlmodel_training_duration'),
        ('manage_datasets', '0002_dataset_head_context_dataset_plots_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_file', models.FileField(upload_to='predictions/')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_results', to='manage_datasets.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_results', to='manage_MLmodels.mlmodel')),
            ],
        ),
    ]
