# Generated by Django 4.2.7 on 2025-10-06 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_datasets', '0002_dataset_head_context_dataset_plots_context_and_more'),
        ('predicting', '0002_alter_predictionresult_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_datasets.dataset'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='prediction_file',
            field=models.FileField(blank=True, null=True, upload_to='predictions/'),
        ),
    ]
